const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
const FETCH_PRODUCTS_REQUESTED = 'FETCH_PRODUCTS_REQUESTED';
const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

const PRODUCT_ADDED_TO_CART = 'PRODUCT_ADDED_TO_CART'
const PRODUCT_DECREASE_COUNT = 'PRODUCT_DECREASE_COUNT'
const PRODUCT_REMOVE_FROM_CART = 'PRODUCT_REMOVE_FROM_CART'
const ADD_NEW_PRODUCT_TO_CART = 'ADD_NEW_PRODUCT_TO_CART'

export {
    FETCH_PRODUCTS_SUCCESS,
    FETCH_PRODUCTS_REQUESTED,
    FETCH_PRODUCTS_FAILURE,
    PRODUCT_ADDED_TO_CART,
    PRODUCT_DECREASE_COUNT,
    PRODUCT_REMOVE_FROM_CART,
    ADD_NEW_PRODUCT_TO_CART
}