const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
const FETCH_PRODUCTS_REQUESTED = 'FETCH_PRODUCTS_REQUESTED';
const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export {
    FETCH_PRODUCTS_SUCCESS,
    FETCH_PRODUCTS_REQUESTED,
    FETCH_PRODUCTS_FAILURE,
}